version: "3.9"  # optional since v1.27.0
services:
  web:
    build: 
      context: . # fine the docker file in current diectory 
      dockerfile: Dockerfile
    image: webapp:2.0 # I want to change the image name
    ports:
      - "80:5000"
    restart: always
    networks: 
     - webnet
     
networks:
  webnet: